
cuddleGifs = ['https://media.giphy.com/media/h4BprYiFYNxRe/giphy.gif',
            'https://media.giphy.com/media/131Q2gKssUNCwM/giphy.gif',
            'https://media.giphy.com/media/wBQa0CjlSySUE/giphy.gif',
            'https://media.giphy.com/media/javHxbM3JgrcY/giphy.gif',
            'https://media.giphy.com/media/yhbzJcQhek0g0/giphy.gif',
            'https://media.giphy.com/media/nTeeb8thSiS0U/giphy.gif',
            'https://media.giphy.com/media/NEuAV9fBdIjuTxex7U/giphy.gif',
            'https://media.giphy.com/media/bAmQn1R4V3owE/giphy.gif',
            'https://media.giphy.com/media/PibhPmQYXZ7HO/giphy.gif',
            'https://media.giphy.com/media/TFTJhIlix4cxVsMVye/giphy.gif',
            'https://media.giphy.com/media/PHZ7v9tfQu0o0/giphy.gif',
            'https://media.giphy.com/media/Y8wCpaKI9PUBO/giphy.gif',
            'https://media.giphy.com/media/C4gbG94zAjyYE/giphy.gif',
            'https://tenor.com/view/sao-sword-art-online-love-kirito-asuna-gif-16542536',
            'https://tenor.com/view/cat-girl-affection-hug-cuddle-clingy-gif-16403937',
            'https://tenor.com/view/anime-cuddle-cute-gif-12668750']

hugGifs = ['https://media.giphy.com/media/VbawWIGNtKYwOFXF7U/giphy.gif',
           'https://media.giphy.com/media/KL7xA3fLx7bna/giphy.gif',
           'https://media.giphy.com/media/gnXG2hODaCOru/giphy.gif',
           'https://media.giphy.com/media/xT1XGQve0LxCblDLr2/giphy.gif',
           'https://media.giphy.com/media/EvYHHSntaIl5m/giphy.gif',
           'https://media.giphy.com/media/VduFvPwm3gfGO8duNN/giphy.gif',
           'https://media.giphy.com/media/llmZp6fCVb4ju/giphy.gif',
           'https://media.giphy.com/media/3oEjI2iHlsotWgYeQg/giphy.gif',
           'https://media.giphy.com/media/QbkL9WuorOlgI/giphy.gif',
           'https://media.giphy.com/media/kwJw7CXcybyTu/giphy.gif',
           'https://media.giphy.com/media/2A75Y6NodD38I/giphy.gif',
           'https://media.giphy.com/media/IRUb7GTCaPU8E/giphy.gif',
           'https://media.giphy.com/media/sUIZWMnfd4Mb6/giphy.gif',
           'https://media.giphy.com/media/4No2q4ROPXO7T6NWhS/giphy.gif',
           'https://media.giphy.com/media/xT1XGPy39lDKJ5Gc5W/giphy.gif',
           'https://media.giphy.com/media/5z5WQEYicNbMFVDjoP/giphy.gif',
           'https://media.giphy.com/media/fgV89nk5uA8lG/giphy.gif'
          ]

slapGifs = ['https://media.giphy.com/media/gSIz6gGLhguOY/giphy.gif',
            'https://media.giphy.com/media/3XlEk2RxPS1m8/giphy.gif',
            'https://media.giphy.com/media/vxvNnIYFcYqEE/giphy.gif',
            'https://media.giphy.com/media/xT8qB7Sbwskk27Rdy8/giphy.gif',
            'https://media.giphy.com/media/mEtSQlxqBtWWA/giphy.gif',
            'https://media.giphy.com/media/Qvwc79OfQOa4g/giphy.gif',
            'https://media.giphy.com/media/wXgBk2fM696gM/giphy.gif',
            'https://media.giphy.com/media/ky95nsSTlpnTG/giphy.gif',
            'https://media.giphy.com/media/M077ZF5IGk3ba/giphy.gif',
            'https://media.giphy.com/media/iIPI1tpT9HcUE/giphy.gif',
            'https://media.giphy.com/media/26uf3m46sDFVPedig/giphy.gif',
            'https://media.giphy.com/media/Zau0yrl17uzdK/giphy.gif',
            'https://media.giphy.com/media/m6etefcEsTANa/giphy.gif',
            'https://media.giphy.com/media/6Fad0loHc6Cbe/giphy.gif',
            'https://media.giphy.com/media/xUNd9HZq1itMkiK652/giphy.gif',
            'https://media.giphy.com/media/RXGNsyRb1hDJm/giphy.gif']

sexyGifs = ['https://media.giphy.com/media/Ol6OyFmFOC1tC/giphy.gif',
            'https://media.giphy.com/media/3o7aDdyoaef41qkn9m/giphy.gif',
            'https://media.giphy.com/media/xT9Igqv2kxpyAtfpEk/giphy.gif',
            'https://media.giphy.com/media/qngVhP9OWogKY/giphy.gif',
            'https://media.giphy.com/media/7NIWde5Bz3d1K0Vevc/giphy.gif',
            'https://media.giphy.com/media/lYXhWufNZEaQg/giphy.gif',
            'https://media.giphy.com/media/OUxiK1L8xXZYc/giphy.gif',
            'https://media.giphy.com/media/11cJpcapJVlMMo/giphy.gif',
            'https://media.giphy.com/media/vRNaul3vyJRgQ/giphy.gif',
            'https://media.giphy.com/media/12SjEUcMRvd9Ru/giphy.gif',
            'https://media.giphy.com/media/l0Iymo6MEqAJfHaso/giphy.gif',
            'https://media.giphy.com/media/MwtHY03ldRPgc/giphy.gif',
            'https://media.giphy.com/media/YQlHpl82dkqd2/giphy.gif',
            'https://media.giphy.com/media/12bF3AWU423YeA/giphy.gif',
            'https://media.giphy.com/media/a6pzK009rlCak/giphy.gif',
            'https://media.giphy.com/media/reoUTXFBTZUek/giphy.gif',
            'https://media.giphy.com/media/YZX4FWwOJTK5W/giphy.gif',
            'https://media.giphy.com/media/ktDkLA5Hp9dM4/giphy.gif',
            'https://media.giphy.com/media/xTiN0B6CgjLydh36U0/giphy.gif',
            'https://media.giphy.com/media/3oKGzwyoQ57enCUmsw/giphy.gif']

kissGifs = ['https://media.giphy.com/media/l2Je2M4Nfrit0L7sQ/giphy.gif',
            'https://media.giphy.com/media/108M7gCS1JSoO4/giphy.gif',
            'https://media.giphy.com/media/l0HU2EeywKGaMJCY8/giphy.gif',
            'https://media.giphy.com/media/10UUe8ZsLnaqwo/giphy.gif',
            'https://media.giphy.com/media/3o7qDVQ2GrFAf1MVgc/giphy.gif',
            'https://media.giphy.com/media/YDB4EF3U6i6IM/giphy.gif',
            'https://media.giphy.com/media/dMYVHzANYb9p6/giphy.gif',
            'https://media.giphy.com/media/l41lK4KlwYYYSSKFG/giphy.gif',
            'https://media.giphy.com/media/fyM2loi1ZpOV2/giphy.gif',
            'https://media.giphy.com/media/d2Z88USw1NYO6sXm/giphy.gif',
            'https://media.giphy.com/media/zkppEMFvRX5FC/giphy.gif',
            'https://media.giphy.com/media/G3va31oEEnIkM/giphy.gif',
            'https://media.giphy.com/media/kU586ictpGb0Q/giphy.gif',
            'https://media.giphy.com/media/flmwfIpFVrSKI/giphy.gif',
            'https://media.giphy.com/media/11rWoZNpAKw8w/giphy.gif',
            'https://media.giphy.com/media/11k3oaUjSlFR4I/giphy.gif',
            'https://media.giphy.com/media/jR22gdcPiOLaE/giphy.gif',
            'https://media.giphy.com/media/11rWoZNpAKw8w/giphy.gif']

beanerGifs = ['https://media.giphy.com/media/1ZDsMU9jIRvDc7Xffc/giphy.gif',
             'https://media.giphy.com/media/DvUyL3AXD1Is0/giphy.gif',
             'https://media.giphy.com/media/3ohs4uPB9ki20XVcTm/giphy.gif',
             'https://media.giphy.com/media/4DRlGnAqcGSmA/giphy.gif',
             'https://media.giphy.com/media/3oFzm86IVVwouEbsty/giphy.gif',
             'https://media.giphy.com/media/2x0tK0ofGXDQXj1r8b/giphy.gif',
             'https://media.giphy.com/media/Su7qfpu8YVBqE/giphy.gif',
             'https://media.giphy.com/media/26FeVR0vyqbBTMeIg/giphy.gif',
             'https://media.giphy.com/media/H8U39O2iDpL2OFZ3OJ/giphy.gif',
             'https://media.giphy.com/media/3TOSyBjcHrs2y28U06/giphy.gif']

crackerGifs = ['https://media.giphy.com/media/n9YYjrKZaoXQY/giphy.gif',
               'https://media.giphy.com/media/j78kwONU9JCZBqJbt9/giphy.gif ',
               'https://media.giphy.com/media/s99lNdV0SCyHu/giphy.gif',
               'https://media.giphy.com/media/RJtGAlPSfJUDxdb2Q0/giphy.gif',
               'https://media.giphy.com/media/YrfrbQM7cpAdcbU6Af/giphy.gif',
               'https://media.giphy.com/media/3o6nUMnp3mDm5DD7dC/giphy.gif',
               'https://media.giphy.com/media/l4FAWxZQS4xZG0k1O/giphy.gif',
               'https://media.giphy.com/media/xT1Ra2hoDISwCdN3H2/giphy.gif',
               'https://media.giphy.com/media/l0HlHR1FEAIKjtGjS/giphy.gif']

gmGifs = ['https://media.giphy.com/media/l2olcETxXQjImhNcm2/giphy.gif',
          'https://media.giphy.com/media/kC8hGmtWz2LMJVPBQ2/giphy.gif',
          'https://media.giphy.com/media/1xm0bJZjPrXaF74GKP/giphy.gif',
          'https://media.giphy.com/media/2bJWG8k0HAktq/giphy.gif',
          'https://media.giphy.com/media/sJ8VmNfrR8XbF3yLkj/giphy.gif',
          'https://media.giphy.com/media/ctDbNtKI1NPj6ZVwrx/giphy.gif',
          'https://media.giphy.com/media/lhhh57Kbxd4IfdYmTw/giphy.gif',
          'https://media.giphy.com/media/3ohc0SH8Y6TJvc2FMI/giphy.gif',
          'https://media.giphy.com/media/MH3y35SMbg2DLnGckG/giphy.gif',
          'https://media.giphy.com/media/h2ZVjT3kt193cxnwm1/giphy.gif']

gnGifs = ['https://media.giphy.com/media/l1J9REbVPRgCVSJb2/giphy.gif',
          'https://media.giphy.com/media/mguPrVJAnEHIY/giphy.gif',
          'https://media.giphy.com/media/qof7GwPnu4zbG/giphy.gif',
          'https://media.giphy.com/media/OjmrBW4ZQbWjkq6RkC/giphy.gif',
          'https://media.giphy.com/media/LmgFqlSj5uZ1PCUaFR/giphy.gif',
          'https://media.giphy.com/media/4NEbxVNYIxraM/giphy.gif',
          'https://media.giphy.com/media/AH1eEn76TUfjMrrz2V/giphy.gif',
          'https://media.giphy.com/media/A8Zrn3MxMQYpKhb72w/giphy.gif',
          'https://media.giphy.com/media/3o7aD4dzlF5nKiGHx6/giphy.gif']

killGifs = ['https://i.imgur.com/b1HcIg4.gif',
            'https://media.giphy.com/media/yNFjQR6zKOGmk/giphy.gif',
            'https://media.giphy.com/media/3oz8xy1gPFHsB6NMDm/giphy.gif',
            'https://media.giphy.com/media/lnakxcfG2MFy/giphy.gif',
            'https://media.giphy.com/media/CiZB6WIjaoXYc/giphy.gif',
            'https://media.giphy.com/media/9tXn7DEOsjifNDEenF/giphy.gif',
            'https://media.giphy.com/media/CLkW1CgQA5xwA/giphy.gif',
            'https://media.giphy.com/media/PnhOSPReBR4F5NT5so/giphy.gif',
            'https://media.giphy.com/media/UcNaNsFk5jLSytk40R/giphy.gif',
            'https://media.giphy.com/media/AaThTI6tAkJcgZylgw/giphy.gif',
            'https://media.giphy.com/media/lrPDCZOAwf2S0k7B8R/giphy.gif'
            ]

cryGifs = ['https://media.giphy.com/media/3o6wrvdHFbwBrUFenu/giphy.gif',
           'https://media.giphy.com/media/OPU6wzx8JrHna/giphy.gif',
           'https://media.giphy.com/media/3o6ZsS8GFJKJeJoRQ4/giphy.gif',
           'https://media.giphy.com/media/Ph8OWoJA2M3eM/giphy.gif',
           'https://media.giphy.com/media/KDRv3QggAjyo/giphy.gif',
           'https://media.giphy.com/media/ckGndVa23sCk9pae4l/giphy.gif',
           'https://media.giphy.com/media/M28rUlcjueKUE/giphy.gif',
           'https://media.giphy.com/media/AauJT0w8cJoSQ/giphy.gif',
           'https://media.giphy.com/media/3o6ZtlMx1JUwf3qYiQ/giphy.gif',
           'https://media.giphy.com/media/ldC94BvZwmiIw/giphy.gif',
           'https://media.giphy.com/media/iJJ6E58EttmFqgLo96/giphy.gif',
           'https://media.giphy.com/media/3ohs4t2IT01ev5F4jK/giphy.gif']

fuckYouGifs = ['https://media.giphy.com/media/XozypzpGakVuX2ciZJ/giphy.gif',
               'https://media.giphy.com/media/QGzPdYCcBbbZm/giphy.gif',
               'https://media.giphy.com/media/xT0GqgBS0IdI3rFXHy/giphy.gif',
               'https://media.giphy.com/media/XHr6LfW6SmFa0/giphy.gif',
               'https://media.giphy.com/media/143cE5FtVmKrNC/giphy.gif',
               'https://media.giphy.com/media/x1kS7NRIcIigU/giphy.gif',
               'https://media.giphy.com/media/yV5xcSTmtVPBS/giphy.gif',
               'https://media.giphy.com/media/13UeVnBP6x05P2/giphy.gif',
               'https://media.giphy.com/media/NBN2nFCVQDCDe/giphy.gif',
               'https://media.giphy.com/media/bOifD9wkVMRxu/giphy.gif',
               'https://media.giphy.com/media/lIjjwfxKNIhoY/giphy.gif',
               'https://media.giphy.com/media/wuk1rlZSkVKfK/giphy.gif',
               'https://media.giphy.com/media/xI6PL9TeKuxgI/giphy.gif',
               'https://media.giphy.com/media/VAYuDQ8ZFYTFC/giphy.gif',
               'https://media.giphy.com/media/3o7WIvmR2b3nNomGTm/giphy.gif',
               'https://media.giphy.com/media/l0IyjB63VEQ2GuTYI/giphy.gif',
               'https://media.giphy.com/media/xT0BKwiAVPV1JHR6Io/giphy.gif',
               'https://media.giphy.com/media/4BXKwKrbZxVNm/giphy.gif',
               'https://media.giphy.com/media/8OJ8T0ZXF7BG8/giphy.gif',
               'https://media.giphy.com/media/21PindEnXnCJpHkQ4g/giphy.gif']

shutUpGifs = ['https://media.tenor.com/images/9072f8795acccc181418d543ba3e6185/tenor.gif',
              'https://media.tenor.com/images/6cc006c1248a9ba3b2f04d982cddd3c2/tenor.gif',
              'https://media.tenor.com/images/e7da4052717b06da48a59eaf51a99105/tenor.gif',
              'https://media.tenor.com/images/64330182971cc893a85fa52e4fe53035/tenor.gif',
              'https://media.tenor.com/images/72d6334d7b64269d1c3aa8ed2c420cca/tenor.gif',
              'https://media.tenor.com/images/9f94d642e7356214c08c0ffcee8bfd74/tenor.gif',
              'https://media.tenor.com/images/221136ca61d7658b796b0fea5cf4e229/tenor.gif',
              'https://media.tenor.com/images/b3d48329028cfeb5b4a7ee9a6aafe82f/tenor.gif',
              'https://media.tenor.com/images/039e1ea4a26121176ced2c3b468b613c/tenor.gif',
              'https://media.tenor.com/images/779c63258287bf5bf2c4e2ed86f43839/tenor.gif',
              'https://media.tenor.com/images/ab3dd9ddb1d058cfc835ebc280aa94b4/tenor.gif',
              'https://media.tenor.com/images/ad15703d6819b78a6a5ffe416b5488ab/tenor.gif',
              'https://media.tenor.com/images/620c6775c1440af8971bf79b12505b97/tenor.gif']

EDPGifs = ['https://c.tenor.com/XZXAZgaDexsAAAAC/edp445-eagles.gif',
           'https://c.tenor.com/OM8U0Y9caVUAAAAM/wtf-edp-huh.gif',
           'https://c.tenor.com/nEmjbJT0hGUAAAAd/5unwo-edp.gif',
           'https://c.tenor.com/BjSjgWS0d2wAAAAC/edp-edp445.gif',
           'https://c.tenor.com/AlywRKRInesAAAAM/edp.gif',
           'https://c.tenor.com/vwVA7UPJOwIAAAAd/edp-i-missed-her-age.gif',
           'https://c.tenor.com/bw4GYFx5mOIAAAAd/edp-edp445.gif',
           'https://c.tenor.com/GqDuEgxhgqAAAAAC/edp-fistbump.gif',
           'https://c.tenor.com/K9QmMWWdk88AAAAC/edp-edp-burner.gif',
           'https://c.tenor.com/T2lMzW9WdicAAAAC/amogli-edp445.gif',
           'https://c.tenor.com/AlywRKRInesAAAAd/edp.gif']

AsianGifs = ['https://media4.giphy.com/media/16Sg1XyCyjfkA/giphy.gif',
             'https://media1.giphy.com/media/dKZRRvQhrT2HS/giphy.gif',
             'https://media4.giphy.com/media/HiGPJdGNFfFyE/giphy.gif',
             'https://media4.giphy.com/media/KiQTBiI77Dpy8/giphy.gif',
             'https://media1.giphy.com/media/7wDEaTbCupuRq/giphy.gif',
             'https://media1.giphy.com/media/PxsTynUW6OVNK/giphy.gif',
             'https://media1.giphy.com/media/l1JojwaIegn6fbgd2/giphy.gif',
             'https://media0.giphy.com/media/26FfgvCYJi6DPaZY4/giphy.gif',
             'https://media4.giphy.com/media/aT8xFndP3Kpeo/giphy.gif',
             'https://media2.giphy.com/media/UQsIt85ldUSskS3i1b/giphy.gif',
             'https://media4.giphy.com/media/LktZs35kNS6KA/giphy.gif']